# Generated by Django 5.1.3 on 2024-11-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='file_size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
