# Generated by Django 5.1.3 on 2024-11-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_sharedfile_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='feature_vector',
            field=models.BinaryField(blank=True, help_text='Serialized feature vector for AI tasks (e.g., similarity search).', null=True),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata about the file (e.g., tags, AI-generated insights).', null=True),
        ),
    ]
