# Generated by Django 5.1.3 on 2024-11-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_sharedfile_feature_vector_sharedfile_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='file_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
