# Generated by Django 5.1.3 on 2025-08-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_sharedfile_file_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='share_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='shared_to',
            field=models.JSONField(default=list),
        ),
    ]
