# Generated by Django 5.1.3 on 2025-08-15 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_sharedfile_file_url_alter_sharedfile_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.CharField(blank=True, max_length=50)),
                ('file_type', models.CharField(max_length=50)),
                ('original_share_type', models.CharField(max_length=50)),
                ('original_share_time', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_description', models.TextField(blank=True, null=True)),
                ('original_file_id', models.IntegerField()),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StarredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.sharedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'file')},
            },
        ),
    ]
