# Generated by Django 5.1.3 on 2025-08-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_trashlog_starredfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starredfile',
            options={'ordering': ['-starred_at']},
        ),
        migrations.AlterModelOptions(
            name='trashlog',
            options={'ordering': ['-deleted_at']},
        ),
    ]
